name: Build Template

on:
  push:
  pull_request:

jobs:
  build-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.9
          cache: 'pip'
      
      - name: Install CLI
        run: python3 -m pip install pros-cli

