name: Build Template

on:
  push:
  pull_request:

jobs:
  build-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          name: lemlib/lemlib
          ref: refs/heads/master

      - name: Install CLI
        run: python3 -m pip install pros-cli
      
      - name: Build template
        run: pros c create-template

